name: face_detection_web
description: "Flutter plugin that implements Google MediaPipe Face Detection"
version: 1.0.0
homepage: https://github.com/CoderJava/face-detection-flutter-web
repository: https://github.com/CoderJava/face-detection-flutter-web

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mlkit_commons: ^0.6.0
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: GoogleMediaPipeFaceDetectionMultiPlatform
        fileName: multi-platform/web/google_mediapipe_face_detection_web.dart